ukaea/openmc_workshop

- README.md
- tasks/task_2/2_example_geometry_viewer_2d.py
Removed task adding shield geometry to central column and resizing blanket inner radius, as raised in #11
> further reduced number of geometry based tasks

- README.md
This adds instructions for windows users, it still needs testing by a few more windows users but better to have something there rather than nothing
> Docker with windows

- parametric_plasma_source/source_sampling.cpp
Merging so that the new docker images using the version of openmc with the dlopen branch merged work
> added seed to prn call

- .circleci/config.yml
- docker_images/Dockerfile_openmc_dagmc
- docker_images/Dockerfile_openmc_dagmc_nndc_dependencies
- docker_images/Dockerfile_workshop
- docker_images/build_docker_images.sh
- docker_images/build_docker_images_no-cache.sh
- docker_images/push_docker.sh
- tasks/task_4/2_example_neutron_flux_tokamak.py
- tasks/task_5/2_example_photon_spectra_tokamak.py
- tasks/task_6/1_example_tritium_production.py
- tasks/task_6/2_example_tritium_production_study.py
- tasks/task_8/1_simulate_with_random_sample.py
- tasks/task_8/openmc_model.py
- tests/test_task_1.py
- tests/test_task_10.py
- tests/test_task_2.py
- tests/test_task_3.py
- tests/test_task_4.py
- tests/test_task_5.py
- tests/test_task_6.py
- tests/test_task_7.py
- tests/test_task_8.py
- tests/test_task_9.py
This adds automated tests (that currently fail) to the workshop
> Adding circleci

- tasks/task_9/2_plot_2d_optimisation_contour.py
added extra points to the task 9 contour plot
> added more marks to contour plot

- tasks/task_1/README.md
- tasks/task_10/README.md
- tasks/task_11/README.md
- tasks/task_2/README.md
- tasks/task_3/README.md
- tasks/task_4/README.md
- tasks/task_5/README.md
- tasks/task_6/README.md
- tasks/task_7/README.md
- tasks/task_8/README.md
- tasks/task_9/README.md
> Add task links

- install_scripts/install_openmc_ubuntu_18.04.sh
Update `OpenMC` and `DAGMC` repository link.
> Github repo link update

- install_scripts/install_openmc_ubuntu_18.04.sh
- tasks/task_10/run_all.sh
- tasks/task_12/make_faceteted_neutronics_model.py
- tasks/task_12/make_unstructured_mesh.py
- tasks/task_12/run_all.sh
actually 2 commits:
one on install scripts
second:  change some path:   /home/shimwell/   to "."                       
python3 instead of python is also safer in run_all.sh
> Tweak file path and installation guide

- Dockerfile
changed the dir to copy after the lat actions report
> copy changed folder to tasks

- tasks/task_1/plotting_utils.py
This small PR removes a few checks that will no longer be needed if https://github.com/openmc-dev/openmc/pull/1684 is merged
> check is not needed with updated openmc.plotter.py

- tasks/task_3/1_plot_neutron_birth_energy.py
- tasks/task_3/1_point_source_plots.ipynb
- tasks/task_3/2_plasma_source_plots.ipynb
- tasks/task_3/2_plot_neutron_birth_location.py
- tasks/task_3/3_plot_neutron_birth_direction.py
- tasks/task_3/4_plot_neutron_birth_location_plasma.py
- tasks/task_3/5_plot_neutron_birth_direction_plasma.py
- tasks/task_3/source_extraction_utils.py
PR which updates plotting scripts to use new parametric plasma source
> using new plasma source

- .circleci/config.yml
- Dockerfile
- README.md
- tasks/task_1/plotting_utils.py
- tests/test_task_1.py
started reworking the tests and aded badges
> added badge

- tasks/task_5/1_example_neutron_spectra.ipynb
- tasks/task_5/2_example_photon_spectra.ipynb
- tasks/task_5/plotting_utils.py
- tasks/task_6/1_example_tritium_production.ipynb
- tasks/task_6/2_example_tritium_production_study.ipynb
converted tasks 5 and 6 to jupyter notebooks
> Converting tasks to jupyter

- Dockerfile
compressed git clones in the dockerfile
> compressed git clones

- .circleci/config.yml
- Dockerfile
> added cd..

- Dockerfile
- install_scripts/install_openmc_embree_double_down.sh
- tasks/task_10_making_CAD_geometry/1_make_CAD_based_neutronics_geometry.ipynb
Adding the construction of CAD geometry from components to the task 10 examples
> Added cad geometry creation tasks

- tasks/task_05_CSG_cell_tally_TBR/1_example_tritium_production.ipynb
- tasks/task_05_CSG_cell_tally_TBR/2_example_tritium_production_study.ipynb
- tasks/task_06_CSG_cell_tally_DPA/1_find_dpa.ipynb
- tasks/task_07_CSG_cell_tally_spectra/1_example_neutron_spectra.ipynb
- tasks/task_07_CSG_cell_tally_spectra/2_example_photon_spectra.ipynb
- tasks/task_08_CSG_mesh_tally/1_example_2d_mesh_tallies.ipynb
- tasks/task_08_CSG_mesh_tally/2_example_3d_mesh_tallies.ipynb
- tasks/task_10_making_CAD_geometry/1_make_CAD_based_neutronics_geometry.ipynb
- tasks/task_11_CAD_cell_tally_fast_flux/1_simulate_CAD_based_neutronics_geometry_with_cell_tally.ipynb
- tasks/task_13_parameter_study_sampling/1_simulate_with_random_sample.ipynb
PR providing more general task updates
> General task updates

- Dockerfile
added python 3.7.8 installation to dockerfile
> added python installation

- Dockerfile
PR to update dockerfile to install cadquery 2 and python 3.7 to allow .solid rendering in jupyter notebooks
> updated cadquery python and jupyter install

- Dockerfile
added tendl to nuclear data to fix task 13 (endf is missing some required isotopes)
> added tendl to nuclear data

- install_scripts/install_openmc_embree_double_down.sh
> minor changes to speed up install

- tasks/task_01_cross_sections/1_isotope_xs_plot.ipynb
- tasks/task_01_cross_sections/2_element_xs_plot.py.ipynb
- tasks/task_01_cross_sections/3_material_xs_plot.ipynb
- tasks/task_01_cross_sections/4_Doppler_broadening.ipynb
Adds more description to tasks
> updated task 1 descriptions

- tasks/task_12_CAD_mesh_fast_flux/making_shapes_and_reactor_completed.py.ipynb
Tidied up the format of geometries.
> updated task 12 :tada:

- tasks/task_01_cross_sections/plotting_utils.py
This PR allows a more flexible approach to plotting cross sections
previously the temperature was hard coded at romm temp.
Not all evaluations have this temperature
so now the code will find the nearest temperature (to room temp) and use that
> method of finding temperature of xs added

- Dockerfile
makes sure we are using double down in dagmc
> added double down

- Dockerfile
- install_scripts/install_miniconda_cadquery_openmc_dagmc_trelis_plugin_OUTDATED.sh
- install_scripts/install_openmc_and_dependencies_LATEST.sh
- install_scripts/install_openmc_embree_double_down_OUTDATED.sh
- install_scripts/install_openmc_ubuntu_18.04.sh
- Include Intel’s Embree ray tracer via the double down project in the new `DAGMC` release.
> Update old and new install-scripts

- Dockerfile
just missing a &&\ and I also moved the rm for moab to after the python install
> added mising end of line and moved moab del

- Dockerfile
removed parametric plasma source pip install and added compile
> added parametric plasma source compile

- Dockerfile
make_watertight was not being found
> added DAGMC/bin to path

- tasks/task_11_CAD_cell_tally_heat/1_simulate_CAD_neutronics_geometry_with_cell_tally_heat.ipynb
changed task 11 to use pymoab instead of trelis
> now using pymoab

- Dockerfile
fixed parametric plasma source pip install by adding in required change of directory
> fixed parametric plasma source pip install

- Dockerfile
this attempts to fix the pymoab and parametric plasma source problems
> keeping moab build dir and trying env for plasam source lib

- README.md
adding a gather town link to the readme
> added gather link

- Dockerfile
trying to reduce the size of the docker file so that the github action no longer runs out of space
> Smaller dockerfile

- Dockerfile
adds a pip install for the plasma source
using local pip install . as the pypi distro is unreliable
> added pip install for the plasma source

- LICENSE
- README.md
videos of ubuntu and windows install
> extra instructions for installation
